'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2443
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2443.
'
Namespace localhost
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="VMSDataXChangeSoap", [Namespace]:="http://tempuri.org/VMSXChange/VMSDataXChange")>  _
    Public Class VMSDataXChange
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/VMSXChange/VMSDataXChange.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VMSXChange/VMSDataXChange/VMSSynchronization", RequestNamespace:="http://tempuri.org/VMSXChange/VMSDataXChange", ResponseNamespace:="http://tempuri.org/VMSXChange/VMSDataXChange", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function VMSSynchronization(ByVal VendorID As String, ByVal VendorPassword As String, ByVal CompanyKey As Integer, ByVal LastSyncDate As Date, ByVal SendAll As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("VMSSynchronization", New Object() {VendorID, VendorPassword, CompanyKey, LastSyncDate, SendAll})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginVMSSynchronization(ByVal VendorID As String, ByVal VendorPassword As String, ByVal CompanyKey As Integer, ByVal LastSyncDate As Date, ByVal SendAll As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("VMSSynchronization", New Object() {VendorID, VendorPassword, CompanyKey, LastSyncDate, SendAll}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndVMSSynchronization(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VMSXChange/VMSDataXChange/UpdateLastSyncDate", RequestNamespace:="http://tempuri.org/VMSXChange/VMSDataXChange", ResponseNamespace:="http://tempuri.org/VMSXChange/VMSDataXChange", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateLastSyncDate(ByVal LastSyncDate As Date) As String
            Dim results() As Object = Me.Invoke("UpdateLastSyncDate", New Object() {LastSyncDate})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginUpdateLastSyncDate(ByVal LastSyncDate As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateLastSyncDate", New Object() {LastSyncDate}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpdateLastSyncDate(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
